# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BanditHijo.dev
email: bandithijo@duck.com
description: Here's where I started writing some notes that someday I will call it, a book
baseurl: '' # the subpath of your site, e.g. /blog
url: https://bandithijo.dev
site: bandithijo.dev
author: Rizqi Nur Assyaufi
keywords: bandithijo, rizqi nur assyaufi, arch linux, vim, neovim, i3wm, dwm, suckless, jekyll, thinkpad, ruby, rails, ruby on rails

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Makassar

# Opengraph
lang: id
logo_author: /assets/img/logo/logo_author.png
image: /assets/img/banner/bndt_banner.png

# Google Analytics
google_analytics: UA-116004889-1
google_tag: G-688BWZGJ84

# Google Site Verification (Webmaster)
google_verify: qXp9Kgb5hIHVp5T9vFOa_motqUmNuF5STbkJKF70wLc

# LazyLoad
lazyload:
  logo_blank: /assets/img/logo/logo_blank.svg
  logo_blank_banner: /assets/img/logo/logo_blank_banner.svg

# Build settings
incremental: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - rouge
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-last-modified-date

# Newsline
# Nilai: true/false
newsline: false

# Navigation Menu on Header
navigation:
  - title: Blog
    url: /blog/
  - title: Note
    url: /note/
  - title: Zet
    url: /zet/
  - title: Vlog
    url: https://www.youtube.com/c/BanditHijo
  - title: Books
    url: /book/
  - title: Lab
    url: /lab/
  - title: Donate
    url: /donate/
  - title: About
    url: /about/

# Sitemap Generator
# Url : https://github.com/kinnetica/jekyll-plugins
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/feed.xml"
    - "/feed/blog.xml"
    - "/feed/vlog.xml"
    - "/feed/python.xml"
  include_posts:
    - "/index.html"

# Jekyll-Feed
# Url : https://github.com/jekyll/jekyll-feed
feed:
  categories:
    - blog
    - note

keep_files:
    - images

# include:
#   - netlify.toml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
  - lazyhandling.rb
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
