merch:
  - title: "T-shirt BanditHijo.dev"
    description: ""
    cover: ""
    wip: true

books:
  - title: "Arch Linux untuk Orang Sibuk"
    description: ""
    cover: "book_arch-linux-untuk-orang-sibuk.png"
    wip: true
